version: "3.9"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    # network_mode: host

  redis:
    image: redis:alpine
    ports: 
      - 6379:6379

  # app:
  #   build: .
  #   container_name: rentx
  #   volumes:
  #     - .:/usr/app
  #   ports: 
  #     - 3333:3333
    # network_mode: host

volumes:
  pgdata:
    driver: local
